apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: worker-node-network-policy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  nodeSelector: 
    type: "supermicro"
  desiredState:
    interfaces:
      - name: eno2.300 
        description: VLAN 300 using eno2
        type: vlan 
        state: up 
        vlan:
          base-iface: eno2
          id: 300
      - name: br300
        description: Bridge to first OCP vlan
        type: linux-bridge 
        state: up 
        ipv4:
          dhcp: false
          enabled: false
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: eno2.300
      - name: eno2.301 
        description: VLAN 301 using eno2
        type: vlan 
        state: up 
        vlan:
          base-iface: eno2
          id: 301
      - name: br301
        description: Bridge to Second OCP vlan
        type: linux-bridge 
        state: up 
        ipv4:
          dhcp: false
          enabled: false
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: eno2.301
