apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master-node-network-policy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  nodeSelector: 
    type: "hpg10"
  desiredState:
    interfaces:
      - name: eno6.300 
        description: VLAN 300 using eno6
        type: vlan 
        state: up 
        vlan:
          base-iface: eno6
          id: 300
      - name: br300
        description: Bridge to first OCP vlan
        type: linux-bridge 
        state: up 
        ipv4:
          dhcp: false
          enabled: false
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: eno6.300
      - name: eno6.301 
        description: VLAN 301 using eno6
        type: vlan 
        state: up 
        vlan:
          base-iface: eno6
          id: 301
      - name: br301
        description: Bridge to Second OCP vlan
        type: linux-bridge 
        state: up 
        ipv4:
          dhcp: false
          enabled: false
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: eno6.301
