apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br301
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br301
  namespace: virt-default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "br301", 
    "type": "cnv-bridge", 
    "bridge": "br301" 
  }'
