apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br300
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br300
  namespace: virt-default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "br300", 
    "type": "cnv-bridge", 
    "bridge": "br300" 
  }'
