apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv04
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /export/openshift/pv04
    server: galadriel.private.opequon.net
    readOnly: false
