apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: node-label-varda
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-superuser
  patches:
    node-label-machine-type:
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: varda.private.opequon.net
      patchTemplate: |
        metadata:
          labels:
            opequon.net/hw-type: sm
      patchType: application/merge-patch+json
