apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: node-label-aule
  namespace: patch-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  serviceAccountRef:
    name: patch-superuser
  patches:
    node-label-machine-type:
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: aule.private.opequon.net
      patchTemplate: |
        metadata:
          labels:
            opequon.net/hw-type: sm
      patchType: application/merge-patch+json
