apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: node-label-elrohir
  namespace: patch-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceAccountRef:
    name: patch-superuser
  patches:
    node-label-machine-type:
      targetObjectRef:
        apiVersion: v1
        kind: Node
        name: elrohir.private.opequon.net
      patchTemplate: |
        metadata:
          labels:
            opequon.net/hw-type: hpeg10
      patchType: application/merge-patch+json
