apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: ocs-disks
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: opequon.net/hw-type
            operator: In
            values:
              - sm
  storageClassName: ocs-disks
  volumeMode: Block
  maxDeviceCount: 10
  deviceInclusionSpec:
    deviceTypes: 
      - disk
    deviceMechanicalProperties:
      - Rotational
    minSize: 1G
    maxSize: 3T
    models:
      - ST1000DM010-2EP1
    vendors:
      - ATA
