kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
data:
  sync.yaml: |                                 
    kind: LDAPSyncConfig
    apiVersion: v1
    url: ldaps://ipa.private.opequon.net
    bindDN: uid=openshift,cn=sysaccounts,cn=etc,dc=private,dc=opequon,dc=net
    bindPassword:
      file: "/etc/secrets/bindPassword"
    ca: "/etc/ldap-ca/ca.crt"
    insecure: false 
    rfc2307:
        groupsQuery:
            baseDN: "cn=groups,cn=accounts,dc=private,dc=opequon,dc=net"
            scope: one
            filter: "(&(objectClass=posixgroup)(cn=ocp-*))"
            derefAliases: never
            pageSize: 0
        groupUIDAttribute: dn 
        groupNameAttributes: [ cn ] 
        groupMembershipAttributes: [ member ] 
        usersQuery:
            baseDN: "cn=users,cn=accounts,dc=private,dc=opequon,dc=net"
            scope: sub
            derefAliases: never
            pageSize: 0
        userUIDAttribute: dn 
        userNameAttributes: [ uid ] 
        tolerateMemberNotFoundErrors: false
        tolerateMemberOutOfScopeErrors: false
