apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: ldap-sync
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-opequon-onprem
    kind: ClusterSecretStore
  target:
    name: ldap-secret
  data:
    - secretKey: bindPassword
      remoteRef:
        key: opequon_onprem/ldap
        property: bindpassword

