apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opequon-custom-ingress-certificate
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-opequon-onprem
    kind: ClusterSecretStore
  target:
    name: opequon-custom-ingress-certificate
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: opequon_onprem/appssl
        property: sslcrt
    - secretKey: tls.key
      remoteRef:
        key: opequon_onprem/appssl
        property: sslkey

