apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEozCCAwugAwIBAgIBATANBgkqhkiG9w0BAQsFADA+MRwwGgYDVQQKDBNQUklW
    QVRFLk9QRVFVT04uTkVUMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkw
    HhcNMjAxMDMwMTY0MDUyWhcNNDAxMDMwMTY0MDUyWjA+MRwwGgYDVQQKDBNQUklW
    QVRFLk9QRVFVT04uTkVUMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkw
    ggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDNf4F7InokLOcNXL2Xlz0L
    9e0WJY4YBam0Q7QxcqgakR8G3JBCyJAkY/YlhGuPHRpnImQRTzmKAbKswaFxO/O9
    rWG80etlyG5BVhqRRo7dUPNH6KpLAgmDkKoKsjVHQpBfUie4ensccyCfPe/M212s
    V8ZHNMjem7645xhLvfgGQN1GsGtHg4BXR1XjWpnxJxoPRIi2vqQT1TiKxJugmJiL
    YOdQ8jFfpPz5gBht0WPjoM1XfjJ2wwb7076IowVnETPecIO/vxHjK0+7s73CKtS5
    DXk+R89vdk3QWJrS4JovPKK3SMSMrgE/DvcLYUYzJbOQeDJCe/GMipSpegOswu4z
    prP5Xpt13I4gvBPrmUxUXQgY0Lt4mDQqRkfZPu8a0E6b6n1JWKSoxiix06e3/2Po
    epccxaSMV2Vuaexp7/KA6N7TGPBUs46tOgV5F7qtNDgSaZEhJKVjFGfOb4D8D5ZE
    S6fO4js7EUaPpnQh4ctzXW0/9tJqQRIEVEmpQbJp/GMCAwEAAaOBqzCBqDAfBgNV
    HSMEGDAWgBTPvP/92jbsU7VA5fBE77NT7S3LezAPBgNVHRMBAf8EBTADAQH/MA4G
    A1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQUz7z//do27FO1QOXwRO+zU+0ty3swRQYI
    KwYBBQUHAQEEOTA3MDUGCCsGAQUFBzABhilodHRwOi8vaXBhLWNhLnByaXZhdGUu
    b3BlcXVvbi5uZXQvY2Evb2NzcDANBgkqhkiG9w0BAQsFAAOCAYEAbX+L50YMidjF
    P5xn6BZXcB4pkWcUFsJzQIBtncP3kGHon8mkrCfUF6ZU5vkXsQBhVzdDmqaNQtwn
    uAxA5QdvHkQg0Xw/NfEG5p69VIEuAUQF4HQRK9Api2m5qgtypq8sTrKkzOUAUtVj
    tPJ9I6zwIlkC+7Jwbn6oXjJTVT8lLtYrudDZXUkudOE6dyur2AsuRU4QkEGgMrf/
    pEV+w7EysofMRRZuz+TKp46b+AQDCbG+cKzF7piFHZaffXi3Wrjz0Q4EniLUyakm
    mWqBBZIgy7VxwFOL69C6J9HB1yRaU02DzOJ6Ju/77ivWAeBR1PmtFs08LavKzjO/
    v+xYZlhjdTP3lMcfSDvUjt8vvm2CEOncY9GKaxdiFhTrP105eYZ7EW8OBEShb23M
    A7OfMbipTTysVYpmkP14jLJEJkYMdtbbLhWVYs1HqXhFpQfRDTjWkKMJ6tENQkyQ
    i3w8EMA7jCivwet3RbdV0qdUpLfpgynbo8KH2fJwqjPMOqVBBBcN
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: opequon-custom-ca-oauth
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Prune=false

