apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: odf-operator-group
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  targetNamespaces:
    - openshift-storage
