apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  channel: "4.8"
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
